apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jpx56fjmc-go 
  janus-idp.io/tekton: jpx56fjmc-go
  backstage.io/kubernetes-id: jpx56fjmc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jpx56fjmc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml